language: node_js
node_js:
  - "8"

before_script:
  - npm install --prefix=dapp
  - npm install --prefix=webapp
  - npm run ethereum --prefix=dapp &

script:
  - npm run test --prefix=dapp
  - npm run test --prefix=webapp

cache:
  directories:
    - "webapp/node_modules"
    - "dapp/node_modules"
